# Generated by Django 4.2.5 on 2023-09-12 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Airport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("airportCode", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Flight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("arrivalTime", models.DateTimeField(auto_now_add=True)),
                ("departureTime", models.DateTimeField(auto_now_add=True)),
                ("duration", models.IntegerField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("status", models.CharField(default="On Time", max_length=2)),
                (
                    "destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flight_destination",
                        to="accounts.airport",
                    ),
                ),
                (
                    "pointOfDeparture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flight_time",
                        to="accounts.airport",
                    ),
                ),
            ],
            options={
                "ordering": (
                    "pointOfDeparture",
                    "arrivalTime",
                    "departureTime",
                    "destination",
                ),
            },
        ),
    ]
