# Generated by Django 4.2.5 on 2023-09-12 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flight",
            name="status",
            field=models.CharField(
                choices=[
                    ("Cancelled", "CANCELLED"),
                    ("Delayed", "DELAYED"),
                    ("On Time", "ON_TIME"),
                ],
                max_length=9,
            ),
        ),
        migrations.CreateModel(
            name="Train",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("arrivalTime", models.DateTimeField(auto_now_add=True)),
                ("departureTime", models.DateTimeField(auto_now_add=True)),
                ("duration", models.IntegerField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Cancelled", "CANCELLED"),
                            ("Delayed", "DELAYED"),
                            ("On Time", "ON_TIME"),
                        ],
                        max_length=9,
                    ),
                ),
                (
                    "destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="train_destination",
                        to="accounts.airport",
                    ),
                ),
                (
                    "pointOfDeparture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="train_time",
                        to="accounts.airport",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
